# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-project:
    name: Build project
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Install MAUI workload
      run: dotnet workload install maui
      
    - name: Build Windows
      run: dotnet build "Music Player Maui/Music Player Maui.csproj" -c Release -f:net7.0-windows10.0.19041.0
    - name: Upload Windows-Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: Music Player Maui/bin/Release/net7.0-windows10.0.19041.0/win10-x64
        retention-days: 1
        
    - name: Build Android
      run: dotnet build "Music Player Maui/Music Player Maui.csproj" -c Release -f:net7.0-android
    
    - name: Upload Android-Artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-build
        path: Music Player Maui/bin/Release/net7.0-android
        retention-days: 1
      
  release-project:
    name: Release Project
    if: ${{ github.event_name == 'push' }}
    runs-on: windows-latest
    permissions: write-all
    needs: build-project
    steps:
    
    - name: Download windows artifact
      uses: actions/download-artifact@v3
      with:
        name: windows-build
        path: ./download/windows

    - name: Archive windows content
      uses: thedoctor0/zip-release@master
      with:
        path: ./download/windows/
        filename: windows-build.zip
        
    - name: Download android artifact
      uses: actions/download-artifact@v3
      with:
        name: android-build
        path: ./download/android

    - name: Archive android content
      uses: thedoctor0/zip-release@master
      with:
        path: ./download/android/
        filename: android-build.zip

    - name: Create Release
      id: create_release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "0.2.${{ github.run_number }}"
        prerelease: true
        title: "v0.2.${{ github.run_number }}"

    - name: Upload Windows Release Asset
      id: upload-windows-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./windows-build.zip
        asset_name: mp-music-player.win10-x64.zip
        asset_content_type: application/zip
        
    - name: Upload Android Release Asset
      id: upload-android-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./android-build.zip
        asset_name: mp-music-player.android.zip
        asset_content_type: application/zip

  #   - name: Create GitHub Release
  #    id: create_release
  #    uses: actions/create-release@v1
  #    env:
  #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #is provided by action, doesn't need to be manually set
  #    with:
  #      tag_name: ${{ github.run_number }}
  #      release_name: Release ${{ github.run_number }}
