# This workflow builds and releases the project on github

# todo: format release log better
# todo: make releases signed by github again
# todo: rename android apk

name: Build and Release

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:

  # building the project for windows and android and uploading the build as artifacts
  build-project:
    name: Build project
    runs-on: windows-latest
    steps:

    # Checks-out repository under $GITHUB_WORKSPACE, so job can access it
    - uses: actions/checkout@v3
      
    # Windows
    - name: Build Windows
      run: dotnet build "MP - Music Player/MP - Music Player.csproj" -c Release -f:net7.0-windows10.0.19041.0
    - name: Upload Windows-Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: MP - Music Player/bin/Release/net7.0-windows10.0.19041.0/win10-x64
        retention-days: 1

    # Android  
    - name: Build Android
      run: dotnet build "MP - Music Player/MP - Music Player.csproj" -c Release -f:net7.0-android
    
    - name: Upload Android-Artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-build
        path: MP - Music Player/bin/Release/net7.0-android
        retention-days: 1

  # Creates GitHub-Release with Release-Notes   
  release-project:
    name: Release Project
    runs-on: windows-latest
    permissions: write-all
    needs: build-project
    steps:
    
    # Need to checkout again
    - uses: actions/checkout@v3
    
    # Download previous artifacts and zip em up
    - name: Download windows artifact
      uses: actions/download-artifact@v3
      with:
        name: windows-build
        path: ./download/windows

    - name: Zip windows build
      uses: thedoctor0/zip-release@master
      with:
        path: ./download/windows/
        filename: windows-build.zip
        
    - name: Download android artifact
      uses: actions/download-artifact@v3
      with:
        name: android-build
        path: ./download/android

    # Creating Release Log
    # Needs to fetch before otherwise doesn't know last commits
    - name: Git Fetch
      shell: bash
      run: git fetch --depth=500

    - name: create release log
      shell: bash
      run: git log $(git describe --tags --abbrev=0)..HEAD --no-merges --oneline > "${{ github.workspace }}\new-in-this-release.log"
      
    - name: show release log file
      run: cat "${{ github.workspace }}\new-in-this-release.log"
      
    - name: workspace directory
      shell: bash
      run: echo "${{ github.workspace }}\new-in-this-release.log"
    
    - name: list files
      run: ls
      
    - name: Receive Version (env.Tag_Name + env.Release_Name)
      run: python ".github/workflows/receive-version.py"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "${{ env.Tag_Name }}"
        name: "${{ env.Release_Name }}"
        prerelease: true
        body_path: "${{ github.workspace }}\\new-in-this-release.log"
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          ./download/android/mp_music_player.mp_music_player-Signed.apk
          windows-build.zip